### ISSUE TITLE
Documentation? Readme?

### ISSUE THREAD

**Issue by laszukdawid** [martius-lab/iCEM#1]
Hi guys,

I just saw your [CoRL 2020 spotlight talk](https://www.youtube.com/watch?v=wuOOIuC1_h4) and thought that the work is interesting. However, in all honesty, it's difficult to extract much information from the code. Do you plan to add some explanation/documentation to this code? I would like to try it but unfortunately I'm unable to invest time into going line by line right now.

Thank you,
D

**Comment by CristinaPin** [comment]
Hi Dawid, I added some comments in the readme (commit f928ad5). Let us know if that helps you to integrate iCEM in your codebase :)

**Comment by laszukdawid** [comment]
Hi Cristina,

Thank you for such a quick reply :) Yes, it does look a lot better. Unfortunately, all of the sudden my priority has switched so I won't be implementing this too soon, but I will return to this.

Apologies if this added unnecessary burden.

Thank you :)
