### ISSUE TITLE
How should I reproduce results in paper?

### ISSUE THREAD

**Issue by HaozhiQi** [martius-lab/iCEM#2]
Hi, thanks for proving the code.

Could I ask how to reproduce numbers reported in paper? For example, for the fpp task, how should I adjust the `settings/fpp/defaults.json` to get your figure 3 results? Do we need to change the `number_of_rollouts` and `training_iterations`?

**Comment by s-bl** [comment]
@HaozhiQi Hey. 

To reproduce figure 3, you have to run the experiment with the different budget settings. The budget translates into different choices of the number of CEM iterations (`controller_params.action_sampler_params.opt_iterations`) and number of simulated trajectories (`controller_params.num_simulated_trajectories`).

You can find the mapping from budget to parameters in table S4 in the appendix.

Best,
Sebastian

**Comment by CristinaPin** [comment]
@HaozhiQi hi! just a supplementary answer from my side :) I think that the easiest thing to do would be to have a file like [this](https://github.com/martius-lab/iCEM/blob/abf8e08e5993eaad2b61d7f56906808de964330a/icem/settings/fpp/i-cem-blitz.json) (which inherits from the generic [fast iCEM](https://github.com/martius-lab/iCEM/blob/abf8e08e5993eaad2b61d7f56906808de964330a/icem/settings/defaults/i-cem-blitz.json)) and where you overwrite the parameters that @s-bl mentioned.
This would look like this:

<pre>
{    
    "inherits_from": [
        "defaults",
        "..defaults.gt_default_env",
	"..defaults.i-cem-blitz"
    ],
    "model_dir": "results/icem/fpp/i-cem-blitz",
    "controller_params": {
        <b>"num_simulated_trajectories": ___,</b>
    	"action_sampler_params": {
            <b>"opt_iterations": ___,</b>
    	    "noise_beta": 3.0
    	}
    }
}
</pre>

which you could simply run like `python main.py settings/fpp/new_budget.json`

Let us know if something is unclear.

**Comment by HaozhiQi** [comment]
@s-bl @CristinaPin Thanks a lot for your clear answers! I think my question is resolved.
